package com.eltp.yuchen.pojo;


import java.io.Serializable;

public class Shares implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SharesCode
     *
     * @mbggenerated
     */

    private String sharescode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SharesName
     *
     * @mbggenerated
     */
    private String sharesname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.TodayOpenPrice
     *
     * @mbggenerated
     */
    private Double todayopenprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.YesterdayClosingPrice
     *
     * @mbggenerated
     */
    private Double yesterdayclosingprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.CurrentPrice
     *
     * @mbggenerated
     */
    private Double currentprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.HighestPrice
     *
     * @mbggenerated
     */
    private Double highestprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.MinimumPrice
     *
     * @mbggenerated
     */
    private Double minimumprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyOne
     *
     * @mbggenerated
     */
    private Double buyone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellOne
     *
     * @mbggenerated
     */
    private Double sellone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.TransactionNum
     *
     * @mbggenerated
     */
    private Integer transactionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.TransactionMoney
     *
     * @mbggenerated
     */
    private Double transactionmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyOneNum
     *
     * @mbggenerated
     */
    private Integer buyonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyOnePrice
     *
     * @mbggenerated
     */
    private Double buyoneprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyTwoNum
     *
     * @mbggenerated
     */
    private Integer buytwonum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyTwoPrice
     *
     * @mbggenerated
     */
    private Double buytwoprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyThreeNum
     *
     * @mbggenerated
     */
    private Integer buythreenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyThreePrice
     *
     * @mbggenerated
     */
    private Double buythreeprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyFourNum
     *
     * @mbggenerated
     */
    private Integer buyfournum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyFourPrice
     *
     * @mbggenerated
     */
    private Double buyfourprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyFiveNum
     *
     * @mbggenerated
     */
    private Integer buyfivenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.BuyFivePrice
     *
     * @mbggenerated
     */
    private Double buyfiveprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellOneNum
     *
     * @mbggenerated
     */
    private Integer sellonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellOnePrice
     *
     * @mbggenerated
     */
    private Double selloneprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellTwoNum
     *
     * @mbggenerated
     */
    private Integer selltwonum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellTwoPrice
     *
     * @mbggenerated
     */
    private Double selltwoprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellThreeNum
     *
     * @mbggenerated
     */
    private Integer sellthreenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellThreePrice
     *
     * @mbggenerated
     */
    private Double sellthreeprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellFourNum
     *
     * @mbggenerated
     */
    private Integer sellfournum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellFourPrice
     *
     * @mbggenerated
     */
    private Double sellfourprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellFiveNum
     *
     * @mbggenerated
     */
    private Integer sellfivenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.SellFivePrice
     *
     * @mbggenerated
     */
    private Double sellfiveprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.Dates
     *
     * @mbggenerated
     */
    private String dates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharesinfo.Times
     *
     * @mbggenerated
     */
    private String times;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SharesCode
     *
     * @return the value of sharesinfo.SharesCode
     *
     * @mbggenerated
     */
    public String getSharescode() {
        return sharescode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SharesCode
     *
     * @param sharescode the value for sharesinfo.SharesCode
     *
     * @mbggenerated
     */
    public void setSharescode(String sharescode) {
        this.sharescode = sharescode == null ? null : sharescode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SharesName
     *
     * @return the value of sharesinfo.SharesName
     *
     * @mbggenerated
     */
    public String getSharesname() {
        return sharesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SharesName
     *
     * @param sharesname the value for sharesinfo.SharesName
     *
     * @mbggenerated
     */
    public void setSharesname(String sharesname) {
        this.sharesname = sharesname == null ? null : sharesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.TodayOpenPrice
     *
     * @return the value of sharesinfo.TodayOpenPrice
     *
     * @mbggenerated
     */
    public Double getTodayopenprice() {
        return todayopenprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.TodayOpenPrice
     *
     * @param todayopenprice the value for sharesinfo.TodayOpenPrice
     *
     * @mbggenerated
     */
    public void setTodayopenprice(Double todayopenprice) {
        this.todayopenprice = todayopenprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.YesterdayClosingPrice
     *
     * @return the value of sharesinfo.YesterdayClosingPrice
     *
     * @mbggenerated
     */
    public Double getYesterdayclosingprice() {
        return yesterdayclosingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.YesterdayClosingPrice
     *
     * @param yesterdayclosingprice the value for sharesinfo.YesterdayClosingPrice
     *
     * @mbggenerated
     */
    public void setYesterdayclosingprice(Double yesterdayclosingprice) {
        this.yesterdayclosingprice = yesterdayclosingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.CurrentPrice
     *
     * @return the value of sharesinfo.CurrentPrice
     *
     * @mbggenerated
     */
    public Double getCurrentprice() {
        return currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.CurrentPrice
     *
     * @param currentprice the value for sharesinfo.CurrentPrice
     *
     * @mbggenerated
     */
    public void setCurrentprice(Double currentprice) {
        this.currentprice = currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.HighestPrice
     *
     * @return the value of sharesinfo.HighestPrice
     *
     * @mbggenerated
     */
    public Double getHighestprice() {
        return highestprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.HighestPrice
     *
     * @param highestprice the value for sharesinfo.HighestPrice
     *
     * @mbggenerated
     */
    public void setHighestprice(Double highestprice) {
        this.highestprice = highestprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.MinimumPrice
     *
     * @return the value of sharesinfo.MinimumPrice
     *
     * @mbggenerated
     */
    public Double getMinimumprice() {
        return minimumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.MinimumPrice
     *
     * @param minimumprice the value for sharesinfo.MinimumPrice
     *
     * @mbggenerated
     */
    public void setMinimumprice(Double minimumprice) {
        this.minimumprice = minimumprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyOne
     *
     * @return the value of sharesinfo.BuyOne
     *
     * @mbggenerated
     */
    public Double getBuyone() {
        return buyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyOne
     *
     * @param buyone the value for sharesinfo.BuyOne
     *
     * @mbggenerated
     */
    public void setBuyone(Double buyone) {
        this.buyone = buyone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellOne
     *
     * @return the value of sharesinfo.SellOne
     *
     * @mbggenerated
     */
    public Double getSellone() {
        return sellone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellOne
     *
     * @param sellone the value for sharesinfo.SellOne
     *
     * @mbggenerated
     */
    public void setSellone(Double sellone) {
        this.sellone = sellone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.TransactionNum
     *
     * @return the value of sharesinfo.TransactionNum
     *
     * @mbggenerated
     */
    public Integer getTransactionnum() {
        return transactionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.TransactionNum
     *
     * @param transactionnum the value for sharesinfo.TransactionNum
     *
     * @mbggenerated
     */
    public void setTransactionnum(Integer transactionnum) {
        this.transactionnum = transactionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.TransactionMoney
     *
     * @return the value of sharesinfo.TransactionMoney
     *
     * @mbggenerated
     */
    public Double getTransactionmoney() {
        return transactionmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.TransactionMoney
     *
     * @param transactionmoney the value for sharesinfo.TransactionMoney
     *
     * @mbggenerated
     */
    public void setTransactionmoney(Double transactionmoney) {
        this.transactionmoney = transactionmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyOneNum
     *
     * @return the value of sharesinfo.BuyOneNum
     *
     * @mbggenerated
     */
    public Integer getBuyonenum() {
        return buyonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyOneNum
     *
     * @param buyonenum the value for sharesinfo.BuyOneNum
     *
     * @mbggenerated
     */
    public void setBuyonenum(Integer buyonenum) {
        this.buyonenum = buyonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyOnePrice
     *
     * @return the value of sharesinfo.BuyOnePrice
     *
     * @mbggenerated
     */
    public Double getBuyoneprice() {
        return buyoneprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyOnePrice
     *
     * @param buyoneprice the value for sharesinfo.BuyOnePrice
     *
     * @mbggenerated
     */
    public void setBuyoneprice(Double buyoneprice) {
        this.buyoneprice = buyoneprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyTwoNum
     *
     * @return the value of sharesinfo.BuyTwoNum
     *
     * @mbggenerated
     */
    public Integer getBuytwonum() {
        return buytwonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyTwoNum
     *
     * @param buytwonum the value for sharesinfo.BuyTwoNum
     *
     * @mbggenerated
     */
    public void setBuytwonum(Integer buytwonum) {
        this.buytwonum = buytwonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyTwoPrice
     *
     * @return the value of sharesinfo.BuyTwoPrice
     *
     * @mbggenerated
     */
    public Double getBuytwoprice() {
        return buytwoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyTwoPrice
     *
     * @param buytwoprice the value for sharesinfo.BuyTwoPrice
     *
     * @mbggenerated
     */
    public void setBuytwoprice(Double buytwoprice) {
        this.buytwoprice = buytwoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyThreeNum
     *
     * @return the value of sharesinfo.BuyThreeNum
     *
     * @mbggenerated
     */
    public Integer getBuythreenum() {
        return buythreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyThreeNum
     *
     * @param buythreenum the value for sharesinfo.BuyThreeNum
     *
     * @mbggenerated
     */
    public void setBuythreenum(Integer buythreenum) {
        this.buythreenum = buythreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyThreePrice
     *
     * @return the value of sharesinfo.BuyThreePrice
     *
     * @mbggenerated
     */
    public Double getBuythreeprice() {
        return buythreeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyThreePrice
     *
     * @param buythreeprice the value for sharesinfo.BuyThreePrice
     *
     * @mbggenerated
     */
    public void setBuythreeprice(Double buythreeprice) {
        this.buythreeprice = buythreeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyFourNum
     *
     * @return the value of sharesinfo.BuyFourNum
     *
     * @mbggenerated
     */
    public Integer getBuyfournum() {
        return buyfournum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyFourNum
     *
     * @param buyfournum the value for sharesinfo.BuyFourNum
     *
     * @mbggenerated
     */
    public void setBuyfournum(Integer buyfournum) {
        this.buyfournum = buyfournum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyFourPrice
     *
     * @return the value of sharesinfo.BuyFourPrice
     *
     * @mbggenerated
     */
    public Double getBuyfourprice() {
        return buyfourprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyFourPrice
     *
     * @param buyfourprice the value for sharesinfo.BuyFourPrice
     *
     * @mbggenerated
     */
    public void setBuyfourprice(Double buyfourprice) {
        this.buyfourprice = buyfourprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyFiveNum
     *
     * @return the value of sharesinfo.BuyFiveNum
     *
     * @mbggenerated
     */
    public Integer getBuyfivenum() {
        return buyfivenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyFiveNum
     *
     * @param buyfivenum the value for sharesinfo.BuyFiveNum
     *
     * @mbggenerated
     */
    public void setBuyfivenum(Integer buyfivenum) {
        this.buyfivenum = buyfivenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.BuyFivePrice
     *
     * @return the value of sharesinfo.BuyFivePrice
     *
     * @mbggenerated
     */
    public Double getBuyfiveprice() {
        return buyfiveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.BuyFivePrice
     *
     * @param buyfiveprice the value for sharesinfo.BuyFivePrice
     *
     * @mbggenerated
     */
    public void setBuyfiveprice(Double buyfiveprice) {
        this.buyfiveprice = buyfiveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellOneNum
     *
     * @return the value of sharesinfo.SellOneNum
     *
     * @mbggenerated
     */
    public Integer getSellonenum() {
        return sellonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellOneNum
     *
     * @param sellonenum the value for sharesinfo.SellOneNum
     *
     * @mbggenerated
     */
    public void setSellonenum(Integer sellonenum) {
        this.sellonenum = sellonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellOnePrice
     *
     * @return the value of sharesinfo.SellOnePrice
     *
     * @mbggenerated
     */
    public Double getSelloneprice() {
        return selloneprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellOnePrice
     *
     * @param selloneprice the value for sharesinfo.SellOnePrice
     *
     * @mbggenerated
     */
    public void setSelloneprice(Double selloneprice) {
        this.selloneprice = selloneprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellTwoNum
     *
     * @return the value of sharesinfo.SellTwoNum
     *
     * @mbggenerated
     */
    public Integer getSelltwonum() {
        return selltwonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellTwoNum
     *
     * @param selltwonum the value for sharesinfo.SellTwoNum
     *
     * @mbggenerated
     */
    public void setSelltwonum(Integer selltwonum) {
        this.selltwonum = selltwonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellTwoPrice
     *
     * @return the value of sharesinfo.SellTwoPrice
     *
     * @mbggenerated
     */
    public Double getSelltwoprice() {
        return selltwoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellTwoPrice
     *
     * @param selltwoprice the value for sharesinfo.SellTwoPrice
     *
     * @mbggenerated
     */
    public void setSelltwoprice(Double selltwoprice) {
        this.selltwoprice = selltwoprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellThreeNum
     *
     * @return the value of sharesinfo.SellThreeNum
     *
     * @mbggenerated
     */
    public Integer getSellthreenum() {
        return sellthreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellThreeNum
     *
     * @param sellthreenum the value for sharesinfo.SellThreeNum
     *
     * @mbggenerated
     */
    public void setSellthreenum(Integer sellthreenum) {
        this.sellthreenum = sellthreenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellThreePrice
     *
     * @return the value of sharesinfo.SellThreePrice
     *
     * @mbggenerated
     */
    public Double getSellthreeprice() {
        return sellthreeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellThreePrice
     *
     * @param sellthreeprice the value for sharesinfo.SellThreePrice
     *
     * @mbggenerated
     */
    public void setSellthreeprice(Double sellthreeprice) {
        this.sellthreeprice = sellthreeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellFourNum
     *
     * @return the value of sharesinfo.SellFourNum
     *
     * @mbggenerated
     */
    public Integer getSellfournum() {
        return sellfournum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellFourNum
     *
     * @param sellfournum the value for sharesinfo.SellFourNum
     *
     * @mbggenerated
     */
    public void setSellfournum(Integer sellfournum) {
        this.sellfournum = sellfournum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellFourPrice
     *
     * @return the value of sharesinfo.SellFourPrice
     *
     * @mbggenerated
     */
    public Double getSellfourprice() {
        return sellfourprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellFourPrice
     *
     * @param sellfourprice the value for sharesinfo.SellFourPrice
     *
     * @mbggenerated
     */
    public void setSellfourprice(Double sellfourprice) {
        this.sellfourprice = sellfourprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellFiveNum
     *
     * @return the value of sharesinfo.SellFiveNum
     *
     * @mbggenerated
     */
    public Integer getSellfivenum() {
        return sellfivenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellFiveNum
     *
     * @param sellfivenum the value for sharesinfo.SellFiveNum
     *
     * @mbggenerated
     */
    public void setSellfivenum(Integer sellfivenum) {
        this.sellfivenum = sellfivenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.SellFivePrice
     *
     * @return the value of sharesinfo.SellFivePrice
     *
     * @mbggenerated
     */
    public Double getSellfiveprice() {
        return sellfiveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.SellFivePrice
     *
     * @param sellfiveprice the value for sharesinfo.SellFivePrice
     *
     * @mbggenerated
     */
    public void setSellfiveprice(Double sellfiveprice) {
        this.sellfiveprice = sellfiveprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.Dates
     *
     * @return the value of sharesinfo.Dates
     *
     * @mbggenerated
     */
    public String getDates() {
        return dates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.Dates
     *
     * @param dates the value for sharesinfo.Dates
     *
     * @mbggenerated
     */
    public void setDates(String dates) {
        this.dates = dates == null ? null : dates.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharesinfo.Times
     *
     * @return the value of sharesinfo.Times
     *
     * @mbggenerated
     */
    public String getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharesinfo.Times
     *
     * @param times the value for sharesinfo.Times
     *
     * @mbggenerated
     */
    public void setTimes(String times) {
        this.times = times == null ? null : times.trim();
    }
}