package com.eltp.yuchen.provide.dao;

import com.eltp.yuchen.pojo.Shares;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
import java.util.Map;

public interface SharesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharesinfo
     *
     * @mbggenerated
     */
    int insert(Shares record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharesinfo
     *
     * @mbggenerated
     */
    int insertSelective(Shares record);

    List findShares();

    List sharestop(@Param(value="top") int top);

    @Select("select  sharescode,sharesname,count(sharesname) as count from sharesinfo where 1=1 group by sharesname,sharescode")
    List<Map<String,Object>> showshnum();
}